# Below code is intended to verify the R installation within the CI/CD environment.
# stages:
#   - test
#
# test_R:
#   stage: test
#   image: rocker/tidyverse:4.4
#   script:
#     - echo "Testing R installation"
#     - R --version
#   only:
#     - main
#     - merge_requests
stages:
  - test

test_R:
  stage: test
  image: rocker/tidyverse:4.4
  script:
    - echo "Testing R CMD Check"
    - R --version

    # Install devtools and other necessary packages
    - R -e 'install.packages("remotes")'
    - R -e 'remotes::install_deps(dependencies = TRUE)'

    # Optionally, install suggested packages if you want a complete check
    - R -e 'install.packages(c("AppliedPredictiveModeling", "spelling"))'

    # Run R CMD check on the package without building the manual
    - R CMD check ./ --no-build-vignettes --no-manual --as-cran

    # Run the devtools tests
    - R -e 'devtools::test()'

    # Install the package
    - R -e 'devtools::install()'

  only:
    - main
    - merge_requests


